add maven yml 3

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -15,3 +15,20 @@ jobs:
         java-version: 1.8
     - name: Build with Maven
       run: mvn -B package --file pom.xml
+  test-oncokb-endpoint:
+    runs-on: ubuntu-latest
+    steps:
+    - name: GET oncokb data
+      env:
+        ONCOKB_TOKEN: ${{ secrets.ONCOKB_TOKEN }}
+      run: |
+        curl -X GET --header 'Accept: application/json' 'http://localhost:38080/annotation/17%3Ag.41242962_41242963insGA'
+        RESPONSE_CODE=`cat curl.out`
+        if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
+        echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
+          exit 1
+        else
+          echo "Request succeeded with expected response code '$OK_RESPONSE_CODE'"
+          exit 0
+        fi
+
