add maven yml 15

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -9,16 +9,14 @@ jobs:
     - name: GET oncokb data
       env:
         ONCOKB_TOKEN: ${{ secrets.ONCOKB_TOKEN }}
-        OK_RESPONSE_CODE: 200
       run: |
-        curl -s -o /dev/null -w "%{http_code}" -X GET --header 'Accept: application/json' 'http://www.genomenexus.org/annotation/17%3Ag.41242962_41242963insGA' > curl.out
-        RESPONSE_CODE=`cat curl.out`
-        echo RESPONSE_CODE
-        if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
-        echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
-          exit 1
-        else
-          echo "Request succeeded with expected response code '$OK_RESPONSE_CODE'"
+        curl -X GET --header 'Accept: application/json' 'http://www.genomenexus.org/annotation/17%3Ag.41242962_41242963insGA'  -w ",http_code:%{http_code}"> curl.out
+        echo '$curl.out'
+        if [[ 'grep 'http_code:200' curl.out' ]]; then
+          echo "Request succeeded with expected response"
           exit 0
+        else
+          echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
+          exit 1
         fi
 
